/* SPDX-License-Identifier: MIT */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const D=require('../src/gravity/dynamics.js'),model=require('../src/model/model.json');
const root=path.resolve(__dirname,'..'),artifacts=path.join(root,'artifacts');
fs.mkdirSync(artifacts,{recursive:true});
const close=(a,b,message)=>assert(Math.abs(a-b)<1e-10,`${message}: ${a} vs ${b}`);
const vectorClose=(a,b,message)=>a.forEach((x,i)=>close(x,b[i],`${message}, J${i+1}`));
(async()=>{
 const base=process.env.SITE_URL||'file://'+path.join(root,'docs/index.html');
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1060},deviceScaleFactor:1}),errors=[],external=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('console',e=>{if(e.type()==='error')errors.push(e.text());});
  await page.route('**/*',route=>{const u=new URL(route.request().url());if(['file:','data:'].includes(u.protocol)||u.origin===new URL(base).origin)route.continue();else{external.push(u.href);route.abort();}});
  if(base.startsWith('file:'))await page.context().setOffline(true);
  await page.goto(base+'#inertia');
  const iframe=page.locator('iframe[title="YAM 惯性矩阵与六关节力矩实验"]'),lab=page.frameLocator('iframe[title="YAM 惯性矩阵与六关节力矩实验"]');
  await lab.locator('#yam-inertia[data-ready="true"]').waitFor();
  const snapshot=()=>lab.locator('#yam-inertia').evaluate(()=>window.yamInertiaSnapshot());
  const initial=await snapshot();
  assert.deepEqual(initial.state.a,[1,0,0,0,0,0]);assert.equal(initial.state.view,'row');
  const independent=D.inverse(model,initial.state.q,Array(6).fill(0),initial.state.a,[0,0,0]).tau;
  vectorClose(initial.inertia,independent,'Published experiment vs independent inverse dynamics');
  assert.equal(await lab.locator('.torque-row').count(),6);
  const canvasBox=await lab.locator('#lab-canvas').boundingBox(),barsBox=await lab.locator('#torque-bars').boundingBox(),formulaBox=await page.locator('#inertia .formula.big').boundingBox();
  assert(canvasBox.y<550&&barsBox.y<550,'The robot and torques precede the first explanation');
  assert(formulaBox.y>canvasBox.y+canvasBox.height,'The formula follows the experiment');
  await page.screenshot({path:path.join(artifacts,'inertia-desktop.png')});
  await lab.locator('#yam-inertia').screenshot({path:path.join(artifacts,'inertia-lab.png')});
  await lab.locator('[data-input="a"]').click();
  await lab.locator('#number-0').fill('2');
  const doubled=await snapshot();assert.deepEqual(doubled.M,initial.M);assert.deepEqual(doubled.gravity,initial.gravity);assert.equal(doubled.computeCount,initial.computeCount);
  vectorClose(doubled.inertia,initial.inertia.map(x=>2*x),'Acceleration scaling');
  await lab.locator('#number-0').fill('-1');vectorClose((await snapshot()).inertia,initial.inertia.map(x=>-x),'Acceleration reversal');
  await lab.locator('[data-preset="1"]').click();await lab.locator('#output-joint').selectOption('2');
  let s=await snapshot();assert.deepEqual(s.state.a,[0,1,0,0,0,0]);assert.equal(s.state.a[2],0);assert(Math.abs(s.inertia[2])>.1,'Zero J3 acceleration still needs a coupling torque');
  assert((await lab.locator('#live-calculation').textContent()).includes('M32'));
  await lab.locator('#number-0').fill('.5');s=await snapshot();vectorClose(s.inertia,s.M.map(row=>.5*row[0]+row[1]),'Multiple acceleration inputs');
  await lab.locator('[data-view="matrix"]').click();await lab.locator('[data-column="2"]').click();
  assert(await lab.locator('html').evaluate(e=>e.scrollWidth<=innerWidth),'Desktop matrix has no horizontal overflow');
  s=await snapshot();assert.deepEqual(s.state.a,[0,0,1,0,0,0]);vectorClose(s.inertia,s.M.map(row=>row[2]),'A unit acceleration extracts a matrix column');
  await lab.locator('[data-cell-row="0"][data-cell-column="2"]').click();
  assert.deepEqual((await snapshot()).state.a,s.state.a,'Inspecting a matrix element preserves the input');
  await lab.locator('#mass-origin > summary').click();
  await lab.locator('#origin-rows tr').first().waitFor();
  const originSum=await lab.locator('#origin-rows tr').evaluateAll(rows=>rows.reduce((sum,row)=>sum+Number(row.cells[3].textContent),0));
  assert(Math.abs(originSum-s.M[0][2])<1e-5,'Per-link contributions add to the selected matrix element');
  await lab.locator('.calculation').screenshot({path:path.join(artifacts,'inertia-matrix.png')});
  await lab.locator('#mass-origin > summary').click();
  await lab.locator('[data-view="row"]').click();
  await lab.locator('[data-input="q"]').click();await lab.locator('#number-2').fill('20');
  const changed=await snapshot();assert(Math.abs(changed.M[0][0]-initial.M[0][0])>.01,'A pose change modifies effective inertia');
  assert.equal(changed.computeCount,initial.computeCount+1);
  await lab.locator('#include-gravity').check();s=await snapshot();
  assert.deepEqual(s.M,changed.M);vectorClose(s.tau,s.inertia.map((x,i)=>x+s.gravity[i]),'Gravity is added to inertia');
  vectorClose(s.tau,D.inverse(model,s.state.q,Array(6).fill(0),s.state.a).tau,'Full instantaneous inverse dynamics');
  await lab.locator('.workspace').screenshot({path:path.join(artifacts,'inertia-gravity.png')});
  await lab.locator('#zero-acceleration').click();s=await snapshot();vectorClose(s.inertia,Array(6).fill(0),'Zero acceleration');vectorClose(s.tau,s.gravity,'Return to gravity compensation');assert.deepEqual(s.M,changed.M);
  await lab.locator('#include-gravity').uncheck();vectorClose((await snapshot()).tau,Array(6).fill(0),'Zero gravity and acceleration');
  await lab.locator('[data-preset="0"]').click();await lab.locator('#reset-pose').click();await lab.locator('#show-acceleration').check();
  const beforeCamera=await snapshot();await lab.locator('#view-top').click();const afterCamera=await snapshot();
  assert.notEqual(afterCamera.state.pitch,beforeCamera.state.pitch);assert.deepEqual(afterCamera.tau,beforeCamera.tau);assert.equal(afterCamera.computeCount,beforeCamera.computeCount);
  await lab.locator('#view-iso').click();
  await lab.locator('[data-input="q"]').click();
  await lab.locator('#range-1').focus();await page.keyboard.press('ArrowRight');assert.notDeepEqual((await snapshot()).M,beforeCamera.M,'Keyboard controls update the pose');
  await page.locator('#inertia .quiz').first().locator('button').nth(1).click();assert((await page.locator('#inertia .quiz-feedback').first().textContent()).startsWith('对。'));
  await page.locator('#inertia .quiz').nth(1).locator('button').first().click();assert((await page.locator('#inertia .quiz-feedback').nth(1).textContent()).startsWith('对。'));
  for(const width of [1024,390,320]){
   await page.setViewportSize({width,height:900});
   await iframe.scrollIntoViewIfNeeded();
   const bodyHeight=await lab.locator('body').evaluate(async e=>{await new Promise(r=>requestAnimationFrame(r));return Math.ceil(e.getBoundingClientRect().height);});
   await page.waitForFunction(height=>Math.abs(document.querySelector('#inertia iframe').clientHeight-(height+4))<2,bodyHeight);
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width}px lesson has no horizontal overflow`);
   assert(await lab.locator('html').evaluate(e=>e.scrollWidth<=innerWidth),`${width}px experiment has no horizontal overflow`);
   await lab.locator('[data-input="a"]').click();
   assert(await lab.locator('.input-head').evaluateAll(rows=>rows.every(e=>e.scrollWidth<=e.clientWidth+1)),`${width}px acceleration controls retain their units`);
   if(width===1024)await lab.locator('.workspace').screenshot({path:path.join(artifacts,'inertia-tablet.png')});
   if(width===390){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(artifacts,'inertia-mobile.png')});await lab.locator('#yam-inertia').screenshot({path:path.join(artifacts,'inertia-lab-mobile.png')});await page.locator('.inertia-geometry').screenshot({path:path.join(artifacts,'inertia-geometry-mobile.png')});}
   await lab.locator('[data-view="matrix"]').click();
   assert(await lab.locator('html').evaluate(e=>e.scrollWidth<=innerWidth),`${width}px matrix scroll stays inside its panel`);
   await lab.locator('#mass-origin > summary').click();
   assert(await lab.locator('html').evaluate(e=>e.scrollWidth<=innerWidth),`${width}px expanded contributions have no page overflow`);
   await lab.locator('#mass-origin > summary').click();await lab.locator('[data-view="row"]').click();
  }
  assert.deepEqual(errors,[],'No browser errors');assert.deepEqual(external,[],'The lesson needs no external resources');
  console.log(JSON.stringify({passed:true,delivery:base.startsWith('file:')?'offline file':'hosted URL',widths:[1440,1024,390,320],checks:['independent inverse dynamics','acceleration scaling and reversal','coupling at zero relative acceleration','matrix columns and multiple inputs','pose dependence','gravity superposition','per-link contributions','camera invariance','keyboard input','lesson quizzes','responsive overflow'],screenshots:artifacts},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
